name: Release

on:
  push:
    branches:
      - main
      - beta
      - next
      - pre


jobs:
  make_release:
    name: Make Release
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Version
        run: |
          semantic-release --generate-notes false --dry-run
        uses: docker://registry.gitlab.com/ayedocloudsolutions/adf:latest
      - name: Make Version
        run: |
          touch CHANGELOG.md
          semantic-release
        uses: docker://registry.gitlab.com/ayedocloudsolutions/adf:latest
      - name: Archive Artifacts
        with:
          name: Versioning
          path: |
            package.json
            CHANGELOG.md
